# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9fa37b4198518ce67667f05db0cd1d2b"
name = "size_norm"
handle = "size-norm"
application_url = "https://size-norm-app.vercel.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,write_metaobjects,write_metaobject_definitions"

[webhooks]
api_version = "2026-04"

  # Handled by: /app/routes/webhooks.app.uninstalled.tsx
  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  # Handled by: /app/routes/webhooks.app.scopes_update.tsx
  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  # Handled by: /app/routes/webhooks.products.create.tsx
  [[webhooks.subscriptions]]
  uri = "/webhooks/products/create"
  topics = ["products/create"]

  # Handled by: /app/routes/webhooks.products.update.tsx
  [[webhooks.subscriptions]]
  uri = "/webhooks/products/update"
  topics = ["products/update"]

[auth]
redirect_urls = [ "https://size-norm-app.vercel.app/auth/callback" ]

[build]
# Keep our production URL on Shopify even when running `shopify app dev`
# locally. If we ever wire up a tunnel for local dev we'll set this to true
# temporarily.
automatically_update_urls_on_dev = false
