import type { SizeScale } from "./types";

/**
 * Seed data for the 28 V1 Atelier scales used by Eleonora Bonucci.
 *
 * Source: `taglie.xlsx` provided by Stefano on 2026-05-08, parsed into
 * `_atelier_scales_raw.txt` in the repo root. Excel-corrupted scales (`#BB`,
 * `CO`, `CP` — labels auto-cast to dates) were recovered as `m/d` strings and
 * confirmed by the merchant.
 *
 * Excluded from V1 (7 scales): `#BZ` (Roman numerals), `#CG` (XS/S/M/L),
 * `#BB` (only 2 labels), `X` (range `35-36`), `Y` (triple range), `BA` and
 * `BB` (Snow Boot ranges). See memory/project_v1_scope.md.
 *
 * The `aliases` map is intentionally minimal: `parseLabel` already normalizes
 * comma↔dot, unicode↔ASCII fractions, and ASCII `1/2` patterns. Aliases here
 * only cover edge cases that the parser can't infer (alternative spellings,
 * legacy formats, etc.).
 *
 * Canonical labels are preserved EXACTLY as they appear in the merchant's
 * xlsx, including unicode glyphs (`½`), commas (`,`), or kid-prefix `K`.
 */
export const ATELIER_SCALES_V1: readonly SizeScale[] = [
  // ─── Numeric pure: bambino ─────────────────────────────────────────────
  {
    sigla: "#BK",
    name: "Bambino Scarpe IT 14-22,5",
    gender: "kid",
    sourceScale: "EU",
    labels: [
      "14",
      "14,5",
      "15",
      "15,5",
      "16",
      "16,5",
      "17",
      "17,5",
      "18",
      "18,5",
      "19",
      "19,5",
      "20",
      "20,5",
      "21",
      "21,5",
      "22",
      "22,5",
      "23",
    ],
    aliases: {},
  },
  {
    sigla: "#BL",
    name: "Bambino Scarpe IT 23-41",
    gender: "kid",
    sourceScale: "EU",
    labels: [
      "22",
      "23",
      "23,5",
      "24",
      "24,5",
      "25",
      "25,5",
      "26",
      "26,5",
      "27",
      "27,5",
      "28",
      "28,5",
      "29",
      "29,5",
      "30",
      "30,5",
      "31",
      "31,5",
      "32",
      "32,5",
      "33",
      "33,5",
      "34",
      "34,5",
      "35",
      "35,5",
      "36",
      "36,5",
      "37",
      "37,5",
      "38",
      "38,5",
      "39",
      "39,5",
      "40",
      "40,5",
      "41",
    ],
    aliases: {},
  },
  {
    sigla: "#CE",
    name: "Bambino Scarpe UK1",
    gender: "kid",
    sourceScale: "UK",
    labels: ["30", "35", "40", "50"],
    aliases: {},
  },
  {
    sigla: "#BN",
    name: "Bambino Scarpe UK2",
    gender: "kid",
    sourceScale: "UK",
    labels: [
      "K4",
      "K5",
      "K6",
      "K7",
      "K8",
      "K9",
      "K10",
      "K11",
      "K12",
      "K13",
      "1",
      "2",
      "3",
      "3.5",
      "4",
      "4.5",
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
      "7.5",
      "8",
    ],
    aliases: {
      k4: "K4",
      k5: "K5",
      k6: "K6",
      k7: "K7",
      k8: "K8",
      k9: "K9",
      k10: "K10",
      k11: "K11",
      k12: "K12",
      k13: "K13",
    },
  },
  {
    sigla: "#BM",
    name: "Bambino Scarpe US",
    gender: "kid",
    sourceScale: "US",
    labels: [
      "K1",
      "K2",
      "K3",
      "K4",
      "K4.5",
      "K5",
      "K5.5",
      "K6",
      "K6.5",
      "K7",
      "K7.5",
      "K8",
      "K8.5",
      "K9",
      "K9.5",
      "K10",
      "K10.5",
      "K11",
      "K11.5",
      "K12",
      "K12.5",
      "K13",
      "K13.5",
      "1",
      "1.5",
      "2",
      "2.5",
      "3",
      "3.5",
      "4",
      "4.5",
      "5",
      "5.5",
      "6",
      "6.5",
      "7",
    ],
    aliases: {},
  },
  // ─── Numeric pure: donna ───────────────────────────────────────────────
  {
    sigla: "DC",
    name: "Scarpe Donna FR",
    gender: "women",
    sourceScale: "EU",
    labels: [
      "35",
      "35½",
      "36",
      "36½",
      "37",
      "37½",
      "38",
      "38½",
      "39",
      "39½",
      "40",
      "40½",
      "41",
      "41½",
      "42",
      "42½",
    ],
    aliases: {},
  },
  {
    sigla: "I",
    name: "Scarpe Donna IT",
    gender: "women",
    sourceScale: "EU",
    labels: [
      "34",
      "34½",
      "35",
      "35½",
      "36",
      "36½",
      "37",
      "37½",
      "38",
      "38½",
      "39",
      "39½",
      "40",
      "40½",
      "41",
      "41½",
      "42",
    ],
    aliases: {},
  },
  {
    sigla: "AD",
    name: "Scarpe Donna UK",
    gender: "women",
    sourceScale: "UK",
    labels: [
      "2",
      "2½",
      "3",
      "3½",
      "4",
      "4½",
      "5",
      "5½",
      "6",
      "6½",
      "7",
      "7½",
      "8",
      "8½",
    ],
    aliases: {},
  },
  {
    sigla: "R",
    name: "Scarpe Donna USA",
    gender: "women",
    sourceScale: "US",
    labels: [
      "3½",
      "4",
      "4½",
      "5",
      "5½",
      "6",
      "6½",
      "7",
      "7½",
      "8",
      "8½",
      "9",
      "9½",
      "10",
      "10½",
      "11",
    ],
    aliases: {},
  },
  {
    sigla: "DD",
    name: "Scarpe FERRAGAMO donna",
    gender: "women",
    sourceScale: "US",
    labels: [
      "3½",
      "4",
      "4½",
      "5",
      "5½",
      "6",
      "6½",
      "7",
      "7½",
      "8",
      "8½",
      "9",
      "9½",
      "10",
      "10½",
      "11",
      "11½",
    ],
    aliases: {},
  },
  // ─── Numeric pure: uomo ────────────────────────────────────────────────
  {
    sigla: "DB",
    name: "Scarpe Uomo FR",
    gender: "men",
    sourceScale: "EU",
    labels: [
      "39",
      "39½",
      "40",
      "40½",
      "41",
      "41½",
      "42",
      "42½",
      "43",
      "43½",
      "44",
      "44½",
      "45",
      "45½",
      "46",
    ],
    aliases: {},
  },
  {
    sigla: "G",
    name: "Scarpe Uomo IT",
    gender: "men",
    sourceScale: "EU",
    labels: [
      "36",
      "38",
      "38½",
      "39",
      "39½",
      "40",
      "40½",
      "41",
      "41½",
      "42",
      "42½",
      "43",
      "43½",
      "44",
      "44½",
      "45",
      "45½",
      "46",
      "47",
    ],
    aliases: {},
  },
  {
    sigla: "SJ",
    name: "Scarpe uomo JP",
    gender: "men",
    sourceScale: "JP_MM",
    labels: [
      "23",
      "24",
      "25",
      "25.5",
      "26",
      "26.5",
      "27",
      "27.5",
      "28",
      "28.5",
      "29",
      "29.5",
      "30",
    ],
    aliases: {},
  },
  {
    sigla: "AQ",
    name: "Scarpe Uomo TF",
    gender: "men",
    sourceScale: "US",
    labels: [
      "6",
      "6½",
      "7",
      "7½",
      "8",
      "8½",
      "9",
      "9½",
      "10",
      "10½",
      "11",
      "11½",
      "12",
      "12½",
      "13",
      "13½",
      "14",
      "14½",
      "15",
      "15½",
      "16",
    ],
    aliases: {},
  },
  {
    sigla: "M",
    name: "Scarpe Uomo UK",
    gender: "men",
    sourceScale: "UK",
    labels: [
      "3",
      "3½",
      "4",
      "4½",
      "5",
      "5½",
      "6",
      "6½",
      "7",
      "7½",
      "8",
      "8½",
      "9",
      "9½",
      "10",
      "10½",
      "11",
      "11½",
      "12",
    ],
    aliases: {},
  },
  {
    sigla: "P",
    name: "Scarpe Uomo USA",
    gender: "men",
    sourceScale: "US",
    labels: [
      "4",
      "4½",
      "5",
      "5½",
      "6",
      "6½",
      "7",
      "7½",
      "8",
      "8½",
      "9",
      "9½",
      "10",
      "10½",
      "11",
      "11½",
      "12",
      "12½",
      "13",
    ],
    aliases: {},
  },
  {
    sigla: "DE",
    name: "Scarpe FERRAGAMO uomo",
    gender: "men",
    sourceScale: "US",
    labels: [
      "5",
      "5½",
      "6",
      "6½",
      "7",
      "7½",
      "8",
      "8½",
      "9",
      "9½",
      "10",
      "10½",
      "11",
      "11½",
      "12",
      "12½",
      "13",
    ],
    aliases: {},
  },
  // ─── Numeric pure: unisex ──────────────────────────────────────────────
  {
    sigla: "BH",
    name: "Scarpe Unisex FR",
    gender: "unisex",
    sourceScale: "EU",
    labels: ["35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45"],
    aliases: {},
  },
  {
    sigla: "AM",
    name: "Scarpe Unisex IT",
    gender: "unisex",
    sourceScale: "EU",
    labels: [
      "35",
      "35½",
      "36",
      "36½",
      "37",
      "37½",
      "38",
      "38½",
      "39",
      "39½",
      "40",
      "40½",
      "41",
      "41½",
      "42",
      "42½",
      "43",
      "43½",
      "44",
      "44½",
      "45",
      "45½",
      "46",
      "46½",
      "47",
    ],
    aliases: {},
  },
  {
    sigla: "AF",
    name: "Scarpe Unisex UK",
    gender: "unisex",
    sourceScale: "UK",
    labels: [
      "3",
      "3½",
      "4",
      "4½",
      "5",
      "5½",
      "6",
      "6½",
      "7",
      "7½",
      "8",
      "8½",
      "9",
      "9½",
      "10",
      "10½",
      "11",
      "11½",
      "12",
    ],
    aliases: {},
  },
  {
    sigla: "AG",
    name: "Scarpe Unisex USA",
    gender: "unisex",
    sourceScale: "US",
    labels: [
      "3",
      "3½",
      "4",
      "4½",
      "5",
      "5½",
      "6",
      "6½",
      "7",
      "7½",
      "8",
      "8½",
      "9",
      "9½",
      "10",
      "10½",
      "11",
      "11½",
      "12",
      "12½",
      "13",
      "13½",
      "14",
      "14½",
      "15",
    ],
    aliases: {},
  },
  {
    sigla: "SUA",
    name: "SCARPE UNISEX ADIDAS (UK)",
    gender: "unisex",
    sourceScale: "UK",
    labels: [
      "3",
      "3½",
      "4",
      "4½",
      "5",
      "5½",
      "6",
      "6½",
      "7",
      "7½",
      "8",
      "8½",
      "9",
      "9½",
      "10",
      "10½",
      "11",
      "11½",
      "12",
    ],
    aliases: {},
  },
  // ─── Double sizing (Hoka and similar) ──────────────────────────────────
  // The `X/Y` labels mean "this shoe is men's US X = women's US Y". For
  // matrix purposes, we use the MEN'S side (X, the left number) as the
  // primary US value. `source_label` preserves the compound form for display.
  {
    sigla: "SH",
    name: "SCARPA HOKA",
    gender: "unisex",
    sourceScale: "DOUBLE",
    labels: [
      "3.5/5",
      "4/5.5",
      "4.5/6",
      "5/6.5",
      "5.5/7",
      "6/7.5",
      "6.5/8",
      "7/8.5",
      "7.5/9",
      "8/9.5",
      "8.5/10",
      "9/10.5",
      "9.5/11",
      "10/11.5",
      "10.5/12",
      "11/12.5",
      "11.5/13",
      "12/13.5",
      "13/14.5",
      "14/15.5",
    ],
    aliases: {},
  },
  {
    sigla: "CO",
    name: "Scarpe unisex doppia hoka",
    gender: "unisex",
    sourceScale: "DOUBLE",
    labels: [
      "4/5",
      "4.5/5.5",
      "5/6",
      "5.5/6.5",
      "6/7",
      "6.5/7.5",
      "7/8",
      "7.5/8.5",
      "8/9",
      "8.5/9.5",
      "9/10",
      "9.5/10.5",
      "10/11",
      "10.5/11.5",
      "11/12",
      "11.5/12.5",
      "12/13",
      "13/14",
      "14/15",
    ],
    aliases: {},
  },
  {
    sigla: "CP",
    name: "Scarpe unisex hoka",
    gender: "unisex",
    sourceScale: "DOUBLE",
    labels: [
      "3/5",
      "4/6",
      "5/7",
      "6/8",
      "7/9",
      "8/10",
      "9/11",
      "10/12",
      "11/13",
      "12/14",
      "13/15",
      "14/16",
    ],
    aliases: {},
  },
  {
    sigla: "#DF",
    name: "Bambino scarpe US Doppia",
    gender: "kid",
    sourceScale: "DOUBLE",
    labels: ["K10/K13.5", "1/6"],
    aliases: {},
  },
  // ─── M/W combined US ───────────────────────────────────────────────────
  // Labels are `M<men>/W<women>` like `M8/W9.5`. We use the men's number for
  // the US matrix column and preserve the full label as `source_label`.
  {
    sigla: "BQ",
    name: "Scarpe USA UO/DO 1.5",
    gender: "unisex",
    sourceScale: "MW_COMBINED",
    labels: [
      "M3/W4.5",
      "M3.5/W5",
      "M4/W5.5",
      "M4.5/W6",
      "M5/W6.5",
      "M5.5/W7",
      "M6/W7.5",
      "M6.5/W8",
      "M7/W8.5",
      "M7.5/W9",
      "M8/W9.5",
      "M8.5/W10",
      "M9/W10.5",
      "M9.5/W11",
      "M10/W11.5",
      "M10.5/W12",
      "M11/W12.5",
      "M11.5/W13",
      "M12/W13.5",
      "M12.5/W14",
      "M13/W14.5",
      "M13.5/W15",
      "M14/W15.5",
    ],
    aliases: {},
  },
  {
    sigla: "BP",
    name: "Scarpe USA UO/DO 2",
    gender: "unisex",
    sourceScale: "MW_COMBINED",
    labels: [
      "M3/W5",
      "M3½/W5½",
      "M4/W6",
      "M4½/W6½",
      "M5/W7",
      "M5½/W7½",
      "M6/W8",
      "M6½/W8½",
      "M7/W9",
      "M7½/W9½",
      "M8/W10",
      "M8½/W10½",
      "M9/W11",
      "M9½/W11½",
      "M10/W12",
      "M10½/W12½",
      "M11/W13",
      "M11½/W13½",
      "M12/W14",
      "M12½/W14½",
      "M13/W15",
      "M13½/W15½",
    ],
    aliases: {},
  },
] as const;

/** Quick lookup by sigla. */
export const ATELIER_SCALES_BY_SIGLA: ReadonlyMap<string, SizeScale> = new Map(
  ATELIER_SCALES_V1.map((s) => [s.sigla, s]),
);
