/**
 * Type definitions for the conversion engine.
 *
 * The engine is pure: no Shopify, no DB, no I/O. It operates on plain data
 * structures so that consumers (webhook handlers in M4, bulk jobs in M5, theme
 * extension data prep in M6) can wire it however they like.
 */

/** Product/scale gender. `unisex` and `kid` scales accept any product gender. */
export type Gender = "men" | "women" | "unisex" | "kid";

/**
 * The "base" scale that a SizeScale's labels are expressed in.
 *
 * `EU`/`US`/`UK`/`JP_MM` cover the four canonical destination columns.
 *
 * `DOUBLE` is for scales whose labels encode two equivalent sizes separated by
 * `/` — typically used by Hoka and Adidas in unisex SKUs. Example label `3.5/5`
 * = men's 3.5 = women's 5.
 *
 * `MW_COMBINED` is for US scales whose labels prefix M/W tokens, like
 * `M8/W9.5`. Used by some American brands for unisex SKUs.
 *
 * For `DOUBLE` and `MW_COMBINED` scales, the conversion matrix primary side is
 * the men's column (the left-hand side of the `/`).
 */
export type SourceScale = "US" | "EU" | "UK" | "JP_MM" | "DOUBLE" | "MW_COMBINED";

/** Display format for fractional sizes in the storefront/PDP. */
export type FractionFormat = "UNICODE" | "DECIMAL" | "ASCII";

/**
 * A SizeScale describes the labels a brand or scale family uses for a product
 * size. The `labels` array is the canonical list (what the merchant uses
 * verbatim in Shopify variant options). The `aliases` map normalizes common
 * input variants (e.g. `38.5` or `38 1/2`) to the canonical label (`38½`).
 */
export interface SizeScale {
  /** Stable identifier including any `#` prefix for kid scales (e.g. `#G`, `DD`, `SH`). */
  sigla: string;
  /** Human-readable name shown in admin UI (e.g. "Scarpe Uomo IT"). */
  name: string;
  gender: Gender;
  sourceScale: SourceScale;
  /** Canonical labels exactly as merchant expects on variant options. */
  labels: string[];
  /** Input variants that normalize to a canonical label. Keys MUST be lowercase. */
  aliases: Record<string, string>;
}

/**
 * One row in a conversion table: maps a source label to the four canonical
 * columns. Any column may be `null` if no equivalent exists at that size point.
 */
export interface ConversionMapping {
  sourceLabel: string;
  us: string | null;
  eu: string | null;
  uk: string | null;
  /** JP mondopoint in millimeters, always an integer. */
  jpMm: number | null;
}

/**
 * A conversion table for a specific scale + brand combination. When `brand` is
 * `null`, this is the generic fallback used when no brand-specific table
 * matches.
 */
export interface ConversionTable {
  scaleSigla: string;
  /** Brand name (case-insensitive at lookup time). `null` for generic table. */
  brand: string | null;
  /**
   * `true` if this table was generated by the seed (in `conversion-tables-seed.ts`)
   * and the merchant has not yet validated it. Stored in DB to flag tables that
   * need merchant review before go-live.
   */
  isSeed: boolean;
  mappings: ConversionMapping[];
}

/**
 * Result of {@link parseLabel}. `canonical` is the form found in `labels` of
 * the scale; `raw` is the input as received.
 */
export interface NormalizedLabel {
  raw: string;
  canonical: string;
}

/**
 * Result of {@link lookupConversion}. The matrix is the four-column conversion
 * for use on variant metafield `size_norm.matrix`. `fromBrandSpecific` lets the
 * caller report which path was taken (useful for analytics + debugging).
 */
export interface ConversionResult {
  matrix: {
    us: string | null;
    eu: string | null;
    uk: string | null;
    jpMm: number | null;
  };
  sourceLabel: string;
  fromBrandSpecific: boolean;
  brandUsed: string | null;
}

/**
 * Stable error codes for failures in the pipeline. These map 1:1 to the
 * `error_code` column of the `ConversionAlert` table (added in M4).
 */
export type ConversionErrorCode =
  | "MISSING_METAFIELD"
  | "GENDER_MISMATCH"
  | "LABEL_NOT_RECOGNIZED"
  | "TABLE_NOT_FOUND"
  | "MAPPING_NOT_FOUND"
  | "SCALE_OUT_OF_SCOPE_V1";

export interface ConversionError {
  code: ConversionErrorCode;
  message: string;
  details?: Record<string, unknown>;
}
